### ISSUE TITLE
[feat] 취소하지 않은 슬롯이 다음 날까지 지속되는 이슈

### ISSUE THREAD

**Issue by reg0145** [42organization/softwave.42gg.server#50]
> ### ISSUE
> * Type: `fix`
> 
> ### TODO
> 1. [x]  전 날 "기다리는 중" 슬롯(227)이 다음 날까지 "기다리는 중"으로 뜨는 이슈(?)

**Comment by nheo9143** [comment]
수동으로 처리하는거 어떨까요 일단...
